{% set name = "pymeep" %}
{% set version = "1.7.0" %}
{% set sha256 = "92974884abe2f7cb3a9e6d91f14b943482936b7d12013075278e03e5be603c46" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: meep-{{ version }}.tar.gz
  url: https://github.com/NanoComp/meep/releases/download/v{{version}}/meep-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - no_using_namespace_std.patch
    - no_complex_literals.patch

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - libctl >=4.1.0
    - harminv
    - mpb >=1.6.1
    - gsl
    - hdf5
    - openblas
    - numpy 1.11.*
  run:
    - python
    - libctl >=4.1.0
    - harminv
    - mpb >=1.6.1
    - {{ pin_compatible('numpy') }}
    - openblas
    - hdf5
    - gsl
    - h5utils
    - h5py
    - scipy

test:
  requires:
    - parallel
  imports:
    - meep
    - meep.mpb
  source_files:
    - libmeepgeom/cyl-ellipsoid-eps-ref.h5
    - python/tests/*.py
    - python/tests/data/*
    - python/examples/mpb_*.py

about:
  home: http:/github.com/stevengj/meep
  license: GPL-2.0
  license_file: LICENSE
  summary: Free finite-difference time-domain (FDTD) software for electromagnetic simulations
  doc_url: http://meep.readthedocs.io
  dev_url: https://github.com/stevengj/meep

extra:
  recipe-maintainers:
    - ChristopherHogan
