travis:
  secure:
    BINSTAR_TOKEN: XR26wuOt+6E0T5ucBFoYHTq2WNNX4RFCHABVeWk1bbniKXFFmz45cLO2BBSBExqN+EAPkWAhfh2Ps9HQKhyy9sUCR3wGstBHtAK5MhMs+ercOu1fjEEa2jcXGzqSTI7HRS1usYhFwPdF/J3vVCc4L7jGz1Sc/VH9VaPWXCc6CfJ0AUuQMe217uht3+7G1sNGoOwxW6RGF0oSaTBc58d7p7MlmHJ8WkdgPJmd+Q7tHiCbKCnSg8QYbu0NqPtOMcTw3b2ISYjYkJiHvzosv+Owv+GptDMdbvvStAc6UTUjtCFTKPhZsMsFub0FH0rONP8/Bt/dsXLmMgFJMdD6sQvuGYGD33LH5IMIpYOpLbRlMhs8UdUgUAYOlKG0ukmeUvQQ0YdiwoVIVP+CgFitnz4p4jo+DWomNCdOHT2bKAG5M/G42xUSLZHybxPlerjYM0olq8LnBo5iH9ndhnYDgcL1rJsjeaHIx3n7+JgpDug8SGCMS/Sod3C2IKAcggYccyPEw8kDJeGRtnPH5BnLxrA96p67Cu1OzwJ5DWwXAJLdosLAkI1usMEBxxzyFkd8FQm3PkI81HVTJWkGNGb77lQlZJNeFK6zywQyJBTATiJJMT17DvmnHy03A3nPkGo7M+vlVxPbtQXqS+YzgtVysPPN83+A4+JPreZ/r/h9Q7lNBnE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
